#spring.application.name=identity-service
server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identify_service"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # debug sql query